name: deploy-aws-lambda
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.x
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Build
        run: dotnet build -c debug
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Serverless Deploy
        run: dotnet lambda deploy-serverless
        
