name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Package with dependencies
        run: |
          mkdir -p deployment
          cp -r ./publish/* ./deployment/
          cp -r ./path-to-external-dll/ ./deployment/
        working-directory: ${{ github.workspace }}
              
      - name: Deploy to AWS Lambda for User Web API
        uses: aws-actions/aws-lambda-deploy@v0
        with:
          function-name: UserWebApi-8Oct
          handler: UserWebApi
          deployment-package: ./deployment/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
