name: deploy-aws-lambda
on:
  push:
    branches:
      - master
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'CPAS-microservices.sln'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.x
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build 
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Package with dependencies
        run: |
          mkdir -p deployment
          cp -r ./publish/* ./deployment/
          cp -r ./path-to-external-dll/ ./deployment/
        working-directory: ${{ github.workspace }}
      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: UserWebApi-8Oct
          handler: UserWebApi
          deployment-package: ./deployment/
